--<ScriptOptions statementTerminator=";"/>

CREATE TABLE HASTA (
		ID INTEGER,
		AD VARCHAR(42),
		DOGUMYILI INTEGER,
		CINSIYET VARCHAR(12),
		ADRES VARCHAR(320),
		EVTEL VARCHAR(82),
		CEPTEL VARCHAR(82),
		EMAIL VARCHAR(82),
		GELISTARIHI VARCHAR(82),
		SONRAKIRANDEVU VARCHAR(82),
		OPERASYON VARCHAR(100),
		UYGULAMALAR LONG VARCHAR
	);

